# Generated by Django 5.0.6 on 2024-09-13 00:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('exportaciones', '0007_rename_anio_exportacion_año'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='exportacion',
            options={'verbose_name': 'Exportación', 'verbose_name_plural': 'Exportaciones'},
        ),
        migrations.AlterField(
            model_name='exportacion',
            name='peso_neto',
            field=models.FloatField(blank=True, null=True),
        ),
    ]
