# Generated by Django 5.0.6 on 2024-09-13 01:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('exportaciones', '0008_alter_exportacion_options_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='exportacion',
            name='año',
            field=models.IntegerField(default=2023, verbose_name='Año'),
            preserve_default=False,
        ),
    ]
