# Generated by Django 5.0.6 on 2024-09-13 01:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('exportaciones', '0010_alter_exportacion_peso_neto'),
    ]

    operations = [
        migrations.AlterField(
            model_name='exportacion',
            name='fob_dolar',
            field=models.FloatField(default=0),
            preserve_default=False,
        ),
    ]
