# Generated by Django 5.0.6 on 2024-09-13 01:31

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('exportaciones', '0011_alter_exportacion_fob_dolar'),
        ('productos', '0005_producto_imagen'),
    ]

    operations = [
        migrations.AlterField(
            model_name='exportacion',
            name='producto',
            field=models.ForeignKey(default=27, on_delete=django.db.models.deletion.CASCADE, to='productos.producto'),
            preserve_default=False,
        ),
    ]
