# Generated by Django 5.0.6 on 2024-09-13 01:31

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('exportaciones', '0012_alter_exportacion_producto'),
        ('geo', '0003_alter_continente_options_alter_pais_options'),
    ]

    operations = [
        migrations.AlterField(
            model_name='exportacion',
            name='destino',
            field=models.ForeignKey(default=101, on_delete=django.db.models.deletion.CASCADE, to='geo.pais'),
            preserve_default=False,
        ),
    ]
