# Generated by Django 5.0.6 on 2024-09-13 00:02

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('geo', '0002_pais_coordenadas'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='continente',
            options={'verbose_name': 'Continente', 'verbose_name_plural': 'Continentes'},
        ),
        migrations.AlterModelOptions(
            name='pais',
            options={'verbose_name': 'Pais ', 'verbose_name_plural': 'Paises'},
        ),
    ]
