# Generated by Django 5.0.6 on 2024-09-10 19:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('trivia', '0002_alter_respuestaincorrecta_question_inc'),
    ]

    operations = [
        migrations.AddField(
            model_name='pregunta',
            name='publicada',
            field=models.BooleanField(default=True),
        ),
    ]
