# Generated by Django 5.0.6 on 2024-09-13 00:02

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('trivia', '0003_pregunta_publicada'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='pregunta',
            options={'verbose_name': 'Pregunta', 'verbose_name_plural': 'Preguntas'},
        ),
        migrations.AlterModelOptions(
            name='respuestaincorrecta',
            options={'verbose_name': 'Respuesta Incorrecta', 'verbose_name_plural': 'Respuestas Incorrectas'},
        ),
    ]
